### ISSUE TITLE
Generic Icon and Size

### ISSUE THREAD

**Issue by marsaray** [marsaray/TPS#2]
The size of the icon and the icon itself are not right at this time. We need it to be a consistent size across the web pages as well as a TPS icon for the project itself that we can use.
- [x] Adjust the size of the icon across all web pages to be uniform
- [x] Create a new icon
- [ ] Adjust background color and text size

**Comment by marsaray** [comment]
Nathaniel can you help me ask the group if anyone wants to draw a logo for TPS?

**Comment by pereznathaniel** [comment]
Created a temporary icon just to see how it will fit. let me know if it actually shows, been having trouble launching.

**Comment by marsaray** [comment]
Nathaniel, thank you very much for doing this. Can we change the background color to something darker and make the text bigger? It looks great otherwise, very creative.
